/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.FundVolunteer;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import medistopBackend.EcoSystem;
import medistopBackend.Enterprise.FundingEnterprise;
import medistopBackend.Funds.Donation.FundsInfo;
import medistopBackend.Funds.Organisation.FundsOrganisationVolunteer;
import medistopBackend.Network.Network;
import medistopBackend.UserAccount.UserAccount;
import medistopBackend.WorkQueue.HospitalFundsRequestWorkQueue;
import medistopBackend.WorkQueue.WorkRequest;
import medistopUtil.SendEmailUtility;

/**
 *
 * @author Zeenia
 */
public class VolunteerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerWorkAreaJPanel
     */
    private JPanel displayJPanel;
    private EcoSystem ecosystem;
    private FundingEnterprise enterprise;
    private Network network;
    private UserAccount userAccount;
 
    public VolunteerWorkAreaJPanel(JPanel displayJPanel,UserAccount account, FundsOrganisationVolunteer orgVolunteer ,FundingEnterprise enterprise, Network network, EcoSystem ecosystem) {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.network = network;
        this.ecosystem = ecosystem;
        
        //Setting label values
        lblVolunteerName.setText(userAccount.getUsername());
        lblFundsOrgName.setText(this.enterprise.getName());
        lblFundsOrgCity.setText(network.getNetworkName());
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblVolunteerName = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        btnPublish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblFundsName = new javax.swing.JLabel();
        lblFundsOrgName = new javax.swing.JLabel();
        lblFundsName1 = new javax.swing.JLabel();
        lblFundsOrgCity = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientCharity = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 0, 51));
        lblWelcome.setText("Welcome ");

        lblVolunteerName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVolunteerName.setText("value");

        lblWelcome1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(204, 0, 51));
        lblWelcome1.setText(", your gift, whether big or small, matters!!");

        btnPublish.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnPublish.setForeground(new java.awt.Color(0, 0, 102));
        btnPublish.setText("Publish Newsletter");
        btnPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublishActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medistopUI.images/charity.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));

        lblFundsName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFundsName.setForeground(new java.awt.Color(0, 0, 102));
        lblFundsName.setText("Funding Organisation Name:");

        lblFundsOrgName.setText("value");

        lblFundsName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFundsName1.setForeground(new java.awt.Color(0, 0, 102));
        lblFundsName1.setText("Funding Organisation Address:");

        lblFundsOrgCity.setText("value");

        tblPatientCharity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PatientName", "Address", "Hospital", "Funds Required", "Newsletter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatientCharity);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblFundsName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblFundsOrgName))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblFundsName1)
                                .addGap(28, 28, 28)
                                .addComponent(lblFundsOrgCity))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFundsName)
                    .addComponent(lblFundsOrgName))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFundsName1)
                    .addComponent(lblFundsOrgCity))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWelcome)
                                .addGap(4, 4, 4)
                                .addComponent(lblVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWelcome1))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWelcome)
                            .addComponent(lblVolunteerName)
                            .addComponent(lblWelcome1))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPublish))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublishActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPatientCharity.getModel();
        int selectedRow = tblPatientCharity.getSelectedRow();
        
        if (selectedRow > -1)
        {
            HospitalFundsRequestWorkQueue request = (HospitalFundsRequestWorkQueue)tblPatientCharity.getValueAt(selectedRow,0);
            
            if(request.getStatus().equalsIgnoreCase("Published"))
            {
                JOptionPane.showMessageDialog(null, "Newsletter Already Published!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                request.setStatus("Published");
                populateTable();
                int count =0;
                for(FundsInfo funds : ecosystem.getDonationDirectory().getFundsDirectory())
                {
                    if(funds.getFundsOrgName().equalsIgnoreCase(enterprise.getName()))
                    {
                        count++;
                    }
                }
        
                String[] receiver = new String[count];
        
                int index =0;
                for(FundsInfo donation : ecosystem.getDonationDirectory().getFundsDirectory())
                {
                    if(donation.getFundsOrgName().equalsIgnoreCase(enterprise.getName()))
                    {
                        receiver[index++] = donation.getDonor().getEmail();
                    }
                }
        
                
                //Defining newsletter details
                String from = "mediStop.newsletter@gmail.com";
                String password = "mediStop@1";
        
                String message = "Hello Donors," +",\n\nGreetings from MediStop! Your gift, whether big or small, matters!!" + "\nListed below are the details of the patient we sponsored for treatment:\n" +"\n"+"Patient Name: "+request.getPatientName()+ "\nHospital Name: " + request.getHospitalName()+"\nHospital City: " + request.getCity() + "\nDonation Provided: "+request.getAmount()+"\n\nRegards,\nTeam MediStop";
                String subject ="News @ MediStop";
                SendEmailUtility.sendEmail(subject, from, password, message, receiver);
        
                JOptionPane.showMessageDialog(null, "Newsletter Successfully Published!!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a case you wish to publish.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
            
    }//GEN-LAST:event_btnPublishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFundsName;
    private javax.swing.JLabel lblFundsName1;
    private javax.swing.JLabel lblFundsOrgCity;
    private javax.swing.JLabel lblFundsOrgName;
    private javax.swing.JLabel lblVolunteerName;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JTable tblPatientCharity;
    // End of variables declaration//GEN-END:variables

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblPatientCharity.getModel();
        model.setRowCount(0);
        
        for(WorkRequest workRequest : network.getFundsRequests().getWorkRequestList())
        {
            HospitalFundsRequestWorkQueue fundsReqWorkQueue = (HospitalFundsRequestWorkQueue)workRequest;
                
            if(fundsReqWorkQueue.getMessage().equalsIgnoreCase("Acknowledged") && fundsReqWorkQueue.getFunderName().equalsIgnoreCase(enterprise.getName()))
            {
                Object[] row = new Object[5];
                row[0] = fundsReqWorkQueue;
                row[1] = fundsReqWorkQueue.getCity();
                row[2] = fundsReqWorkQueue.getHospitalName();
                row[3] = fundsReqWorkQueue.getAmount();
                row[4] = fundsReqWorkQueue.getStatus();
                
                model.addRow(row);
            }
        }          
    }
}
