/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.BloodBank;

import medistopBackend.Bloodbank.Organisation.HeadsOrganisation;
import medistopBackend.EcoSystem;
import medistopBackend.Enterprise.BloodbankEnterprise;
import medistopBackend.Network.Network;
import medistopBackend.UserAccount.UserAccount;
import medistopBackend.Hospital.Organisation.HospitalOrganisationAttendant;
import medistopUI.attendant.AttendantWorkAreaPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Virendra Rathore
 */
public class HeadBloodBankMainPageJPanel extends javax.swing.JPanel {
    private JPanel showPanel;
    private UserAccount userAccount;
    private HeadsOrganisation headsOrganisation;
    private EcoSystem ecoSystem;
    private Network network;
    private BloodbankEnterprise enterprise;
    /**
     * Creates new form BloodBankInchargeLandingJPanel
     */
   
    public HeadBloodBankMainPageJPanel(JPanel showPanel, UserAccount account, HeadsOrganisation headsOrganisation, BloodbankEnterprise bloodbankEnterprise, Network network, EcoSystem ecoSystem) {
        initComponents();
        this.showPanel=showPanel;
        this.headsOrganisation = headsOrganisation;
        this.userAccount = account;
        this.enterprise = bloodbankEnterprise;
        this.ecoSystem = ecoSystem;
        this.network=network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewRequestjButton = new javax.swing.JButton();
        GoToInventoryjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("BBI Landing Area"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewRequestjButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewRequestjButton.setForeground(new java.awt.Color(0, 51, 153));
        ViewRequestjButton.setText("View Requests");
        ViewRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRequestjButtonActionPerformed(evt);
            }
        });
        add(ViewRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 125, 220, 66));

        GoToInventoryjButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GoToInventoryjButton.setForeground(new java.awt.Color(0, 51, 153));
        GoToInventoryjButton.setText("Go To Inventory");
        GoToInventoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToInventoryjButtonActionPerformed(evt);
            }
        });
        add(GoToInventoryjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 209, 220, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("BLOOD BANK INCHARGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRequestjButtonActionPerformed
        
         HeadBloodBankWorkAreaJPanel headBloodBankWorkAreaPanel = new HeadBloodBankWorkAreaJPanel(showPanel,userAccount,headsOrganisation,enterprise,network,ecoSystem);
        showPanel.add("HeadBloodBankWorkAreaJPanel", headBloodBankWorkAreaPanel);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.next(showPanel);
        
               
    }//GEN-LAST:event_ViewRequestjButtonActionPerformed

    private void GoToInventoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToInventoryjButtonActionPerformed
        // TODO add your handling code here:
        BloodBankStorageJPanel bloodBankStoragePanel = new BloodBankStorageJPanel(showPanel,userAccount,headsOrganisation,enterprise,network,ecoSystem);
        showPanel.add("BloodBankStorageJPanel", bloodBankStoragePanel);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.next(showPanel);
        
        
    }//GEN-LAST:event_GoToInventoryjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToInventoryjButton;
    private javax.swing.JButton ViewRequestjButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
