/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.admin;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import medistopBackend.Employee.Employee;
import medistopBackend.Enterprise.Enterprise;
import medistopBackend.Organisation.Organisation;
import medistopBackend.Organisation.Organisation.Type;
import medistopBackend.Organisation.OrganisationDirectory;
import medistopBackend.Role.Role;
import medistopBackend.UserAccount.UserAccount;

/**
 *
 * @author Zeenia
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {
    
    private JPanel displayJPanel;
    private Enterprise enterprise;
    private OrganisationDirectory organizationDirectory;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(JPanel displayJPanel, Enterprise enterprise) {
       
        initComponents();
        this.displayJPanel = displayJPanel;
        this.enterprise = enterprise;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
        
        populateManageOrganisationCombo();
        populateUserOrganizationCombo();
        populateEmployeeViewOrgCombo();
        populateEmployeeUpdateOrgCombo();
        populateManageUserTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        donationTabbedPane = new javax.swing.JTabbedPane();
        manageOrgPanel = new javax.swing.JPanel();
        deliveryDirLabel = new javax.swing.JLabel();
        menuItemName6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageOrg = new javax.swing.JTable();
        deliveryDirLabel5 = new javax.swing.JLabel();
        btnCreateOrg = new javax.swing.JButton();
        comboManageOrg = new javax.swing.JComboBox();
        manageUserPanel1 = new javax.swing.JPanel();
        deliveryDirLabel6 = new javax.swing.JLabel();
        helpTextLabel1 = new javax.swing.JLabel();
        deliveryDirLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        menuItemName12 = new javax.swing.JLabel();
        menuItemName13 = new javax.swing.JLabel();
        menuItemName14 = new javax.swing.JLabel();
        empNameTF = new javax.swing.JTextField();
        deliveryDirLabel9 = new javax.swing.JLabel();
        btnAddEmployee = new javax.swing.JButton();
        comboViewEmpOrg = new javax.swing.JComboBox();
        comboUpdateEmpOrg = new javax.swing.JComboBox();
        manageUserPanel = new javax.swing.JPanel();
        deliveryDirLabel4 = new javax.swing.JLabel();
        helpTextLabel = new javax.swing.JLabel();
        deliveryDirLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        menuItemName7 = new javax.swing.JLabel();
        menuItemName8 = new javax.swing.JLabel();
        menuItemName9 = new javax.swing.JLabel();
        menuItemName10 = new javax.swing.JLabel();
        menuItemName11 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        deliveryDirLabel10 = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        comboUserEmployee = new javax.swing.JComboBox();
        comboUserRole = new javax.swing.JComboBox();
        comboUserOrganisation = new javax.swing.JComboBox();

        donationTabbedPane.setForeground(new java.awt.Color(0, 0, 102));
        donationTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        manageOrgPanel.setBackground(new java.awt.Color(255, 255, 255));

        deliveryDirLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel.setText("MANAGE ORGANISATION");

        menuItemName6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName6.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName6.setText("Organisation Type:");

        tblManageOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organisation ID", "Organisation Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageOrg);

        deliveryDirLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel5.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel5.setText("ADMIN WORK AREA");

        btnCreateOrg.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnCreateOrg.setForeground(new java.awt.Color(0, 0, 102));
        btnCreateOrg.setText("Create Organisation Role");
        btnCreateOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageOrgPanelLayout = new javax.swing.GroupLayout(manageOrgPanel);
        manageOrgPanel.setLayout(manageOrgPanelLayout);
        manageOrgPanelLayout.setHorizontalGroup(
            manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrgPanelLayout.createSequentialGroup()
                .addGroup(manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageOrgPanelLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(deliveryDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageOrgPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageOrgPanelLayout.createSequentialGroup()
                                .addComponent(menuItemName6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboManageOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageOrgPanelLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(deliveryDirLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageOrgPanelLayout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(btnCreateOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        manageOrgPanelLayout.setVerticalGroup(
            manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrgPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(deliveryDirLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deliveryDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(manageOrgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName6)
                    .addComponent(comboManageOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnCreateOrg)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Manage Organisation", manageOrgPanel);

        manageUserPanel1.setBackground(new java.awt.Color(255, 255, 255));

        deliveryDirLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel6.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel6.setText("VIEW EMPLOYEE");

        helpTextLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helpTextLabel1.setForeground(new java.awt.Color(0, 0, 102));
        helpTextLabel1.setText(" ");

        deliveryDirLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel8.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel8.setText("ADMIN WORK AREA");

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEmployee);

        menuItemName12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName12.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName12.setText("Select Organisation:");

        menuItemName13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName13.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName13.setText("Select Organisation:");

        menuItemName14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName14.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName14.setText("Employee Name:");

        deliveryDirLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel9.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel9.setText("UPDATE/CREATE EMPLOYEE");

        btnAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(0, 0, 102));
        btnAddEmployee.setText("ADD EMPLOYEE");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        comboViewEmpOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboViewEmpOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageUserPanel1Layout = new javax.swing.GroupLayout(manageUserPanel1);
        manageUserPanel1.setLayout(manageUserPanel1Layout);
        manageUserPanel1Layout.setHorizontalGroup(
            manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserPanel1Layout.createSequentialGroup()
                .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deliveryDirLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(manageUserPanel1Layout.createSequentialGroup()
                                .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(helpTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(menuItemName12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(comboViewEmpOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50))))
                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(deliveryDirLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                        .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageUserPanel1Layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(menuItemName14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUserPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(menuItemName13)
                                .addGap(31, 31, 31)))
                        .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboUpdateEmpOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(deliveryDirLabel9))
                    .addGroup(manageUserPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        manageUserPanel1Layout.setVerticalGroup(
            manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(deliveryDirLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deliveryDirLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName12)
                    .addComponent(comboViewEmpOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(helpTextLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(deliveryDirLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuItemName13)
                    .addComponent(comboUpdateEmpOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuItemName14))
                .addGap(27, 27, 27)
                .addComponent(btnAddEmployee)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Manage Employee", manageUserPanel1);

        manageUserPanel.setBackground(new java.awt.Color(255, 255, 255));

        deliveryDirLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel4.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel4.setText("VIEW USER");

        helpTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helpTextLabel.setForeground(new java.awt.Color(0, 0, 102));
        helpTextLabel.setText(" ");

        deliveryDirLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel7.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel7.setText("ADMIN WORK AREA");

        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userJTable);

        menuItemName7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName7.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName7.setText("Organisation:");

        menuItemName8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName8.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName8.setText("Employee:");

        menuItemName9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName9.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName9.setText("Role:");

        menuItemName10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName10.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName10.setText("Username:");

        menuItemName11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName11.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName11.setText("Password:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        deliveryDirLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel10.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel10.setText("UPDATE/CREATE USER");

        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnCreateUser.setForeground(new java.awt.Color(0, 0, 102));
        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        comboUserOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUserOrganisationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageUserPanelLayout = new javax.swing.GroupLayout(manageUserPanel);
        manageUserPanel.setLayout(manageUserPanelLayout);
        manageUserPanelLayout.setHorizontalGroup(
            manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserPanelLayout.createSequentialGroup()
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deliveryDirLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(manageUserPanelLayout.createSequentialGroup()
                                .addComponent(helpTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(manageUserPanelLayout.createSequentialGroup()
                            .addGap(343, 343, 343)
                            .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                                        .addComponent(menuItemName11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                                        .addComponent(menuItemName8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(comboUserEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(manageUserPanelLayout.createSequentialGroup()
                                    .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(menuItemName10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(menuItemName9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUserPanelLayout.createSequentialGroup()
                            .addGap(312, 312, 312)
                            .addComponent(menuItemName7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboUserOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(deliveryDirLabel10))
                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(deliveryDirLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        manageUserPanelLayout.setVerticalGroup(
            manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(deliveryDirLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(deliveryDirLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageUserPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(helpTextLabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(deliveryDirLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuItemName7)
                    .addComponent(comboUserOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName8)
                    .addComponent(comboUserEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName9)
                    .addComponent(comboUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuItemName10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName11)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnCreateUser)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Manage User", manageUserPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donationTabbedPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(donationTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1334, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1079, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnCreateOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrgActionPerformed
        // TODO add your handling code here:
        Type type = (Type) comboManageOrg.getSelectedItem();
        organizationDirectory.createOrganisation(type);
        populateManageOrganisationTable();
        populateEmployeeUpdateOrgCombo();
        populateManageOrganisationCombo();
        populateUserOrganizationCombo();
        populateEmployeeViewOrgCombo();
       
        
        JOptionPane.showMessageDialog(null, "Organisation Added Successfully!!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCreateOrgActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        Organisation organisation = (Organisation) comboUpdateEmpOrg.getSelectedItem();
        String name = empNameTF.getText();
        
        if(!name.isEmpty())  {
        organisation.getEmployeeDirectory().addEmployee(name);
        populateEmployeeTable(organisation);
        JOptionPane.showMessageDialog(null,"Employee Added Successfully!!","Success",JOptionPane.INFORMATION_MESSAGE);
        txtUsername.setText("");
         }
        
        else
        { 
        JOptionPane.showMessageDialog(null,"Please enter name of the Employee!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        
       Organisation organisation = (Organisation) comboUserOrganisation.getSelectedItem();
        Employee employee = (Employee) comboUserEmployee.getSelectedItem();
        Role role = (Role) comboUserRole.getSelectedItem();
        String userName = txtUsername.getText();
        String password = txtPassword.getText();
//        if(!userName.isEmpty() ||!password.isEmpty())
//        {
//            boolean result = organisation.getUserAccountDirectory().ifUniqueUsername(userName);
//       
//        if(result == true)
//        {
//            organisation.getUserAccountDirectory().newUserAccount(userName, password, employee, role);
//            JOptionPane.showMessageDialog(null, "User details added successfully!! ","Success", JOptionPane.INFORMATION_MESSAGE);
//            resetFields();
//            populateManageUserTable();
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "UserName not available. \n Please try a different username!","Error", JOptionPane.ERROR_MESSAGE);
//            resetFields();
//        }
//        
//        }
//        else{
//        JOptionPane.showMessageDialog(null, "Please enter details! ","Success", JOptionPane.INFORMATION_MESSAGE);
//        }

        if(userName.isEmpty()==true ||password.isEmpty()==true )
        {
        JOptionPane.showMessageDialog(null, "Please Enter Details ","Success", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else{
        boolean result = organisation.getUserAccountDirectory().ifUniqueUsername(userName);
        
        if(result == true)
        {
            organisation.getUserAccountDirectory().newUserAccount(userName, password, employee, role);
            JOptionPane.showMessageDialog(null, "Successfully recorded the User Details ","Success", JOptionPane.INFORMATION_MESSAGE);
            
            txtUsername.setText("");
            txtPassword.setText("");
            
            populateManageUserTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "UserName already exist. \n Please Select a different one.","Error", JOptionPane.ERROR_MESSAGE);
            txtUsername.setText("");
            txtPassword.setText("");
        }
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void comboViewEmpOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboViewEmpOrgActionPerformed
        // TODO add your handling code here:
         Organisation organisation = (Organisation) comboViewEmpOrg.getSelectedItem();
        if (organisation != null){
            populateEmployeeTable(organisation);
        }
    }//GEN-LAST:event_comboViewEmpOrgActionPerformed

    private void comboUserOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUserOrganisationActionPerformed
        // TODO add your handling code here:
         Organisation organisation = (Organisation) comboUserOrganisation.getSelectedItem();
        if (organisation != null){
            populateUserEmployeeCombo(organisation);
            populateUserRoleCombo(organisation);
        }
    }//GEN-LAST:event_comboUserOrganisationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnCreateOrg;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox comboManageOrg;
    private javax.swing.JComboBox comboUpdateEmpOrg;
    private javax.swing.JComboBox comboUserEmployee;
    private javax.swing.JComboBox comboUserOrganisation;
    private javax.swing.JComboBox comboUserRole;
    private javax.swing.JComboBox comboViewEmpOrg;
    private javax.swing.JLabel deliveryDirLabel;
    private javax.swing.JLabel deliveryDirLabel10;
    private javax.swing.JLabel deliveryDirLabel4;
    private javax.swing.JLabel deliveryDirLabel5;
    private javax.swing.JLabel deliveryDirLabel6;
    private javax.swing.JLabel deliveryDirLabel7;
    private javax.swing.JLabel deliveryDirLabel8;
    private javax.swing.JLabel deliveryDirLabel9;
    private javax.swing.JTabbedPane donationTabbedPane;
    private javax.swing.JTextField empNameTF;
    private javax.swing.JLabel helpTextLabel;
    private javax.swing.JLabel helpTextLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel manageOrgPanel;
    private javax.swing.JPanel manageUserPanel;
    private javax.swing.JPanel manageUserPanel1;
    private javax.swing.JLabel menuItemName10;
    private javax.swing.JLabel menuItemName11;
    private javax.swing.JLabel menuItemName12;
    private javax.swing.JLabel menuItemName13;
    private javax.swing.JLabel menuItemName14;
    private javax.swing.JLabel menuItemName6;
    private javax.swing.JLabel menuItemName7;
    private javax.swing.JLabel menuItemName8;
    private javax.swing.JLabel menuItemName9;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblManageOrg;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables

    /*
    Methods for Manage Organisation Panel
    */
    private void populateManageOrganisationCombo()
    {
        comboManageOrg.removeAllItems();
        
        if(enterprise.getEnterpriseClassification().equals(Enterprise.EnterpriseClassification.Hospital))
        {
            for (Type type : Organisation.Type.values())
            {
                if (type.getValue().equals(Type.Doctor.getValue()) || type.getValue().equals(Type.Attendant.getValue()) || type.getValue().equals(Type.Assistant.getValue()))
                {
                    comboManageOrg.addItem(type);
                }
            }
        }
        
        else if(enterprise.getEnterpriseClassification().equals(Enterprise.EnterpriseClassification.Bloodbank))
        {
            for (Type type : Organisation.Type.values())
            {
                if (type.getValue().equals(Type.BloodBankHead.getValue()))
                {
                    comboManageOrg.addItem(type);
                }
            }
        }
        
        else if(enterprise.getEnterpriseClassification().equals(Enterprise.EnterpriseClassification.Funds))
        {
            for (Type type : Organisation.Type.values())
            {
                if (type.getValue().equals(Type.Volunteer.getValue()) || type.getValue().equals(Type.Manager.getValue()))
                {
                    comboManageOrg.addItem(type);
                }
            }
        }
    }
    
    //Table to see organisation details
    private void populateManageOrganisationTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblManageOrg.getModel();
        model.setRowCount(0);
        
        for (Organisation organization : organizationDirectory.getOrganizationList())
        {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }

    
    /*
    Methods for Manage User Panel
    */
    public void populateUserOrganizationCombo() {
       comboUserOrganisation.removeAllItems();

        for (Organisation organisation : enterprise.getOrganizationDirectory().getOrganizationList()) {
            comboUserOrganisation.addItem(organisation);
        }
    }
    
    public void populateUserEmployeeCombo(Organisation organization){
        comboUserEmployee.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeDirectory()){
            comboUserEmployee.addItem(employee);
        }
    }
    
    private void populateUserRoleCombo(Organisation organization){
        comboUserRole.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            comboUserRole.addItem(role);
        }
    }
    
    //Table to see user details
    public void populateManageUserTable() {

        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();

        model.setRowCount(0);

        for (Organisation organisation : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount userAccount : organisation.getUserAccountDirectory().getUserAccountDirectory()) {
                Object row[] = new Object[2];
                row[0] = userAccount;
                row[1] = userAccount.getRole();
                ((DefaultTableModel) userJTable.getModel()).addRow(row);
            }
        }
    }
    
    /*
    Methods for Manage Employee Panel
    */
    public void populateEmployeeViewOrgCombo()
    {
        comboViewEmpOrg.removeAllItems();
            for (Organisation organisation : organizationDirectory.getOrganizationList())
            {
                comboViewEmpOrg.addItem(organisation);
            }
    }
    
    public void populateEmployeeUpdateOrgCombo(){
        comboUpdateEmpOrg.removeAllItems();
        
        for (Organisation organisation : organizationDirectory.getOrganizationList())
        {
            comboUpdateEmpOrg.addItem(organisation);
        }
    }
    
    //Table to see employee details
    private void populateEmployeeTable(Organisation organization){
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeDirectory())
        {
            Object[] row = new Object[2];
            row[0] = employee.getEmpId();
            row[1] = employee.getEmployeeName();
            model.addRow(row);
        }
    }
   
    //Resetting Fields
    public void resetFields(){
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
}
