/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.SystemAdminWorkArea;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import medistopBackend.EcoSystem;
import medistopBackend.UserData.PatientData;

/**
 *
 * @author aviti
 */
public class ManagePatientJPanel extends javax.swing.JPanel {
JPanel displayJPanel;
EcoSystem ecosystem;
    /**
     * Creates new form ManagePatientJPanel
     */
    public ManagePatientJPanel(JPanel displayJPanel, EcoSystem ecosystem) {
        initComponents();
        this.displayJPanel=displayJPanel;
        this.ecosystem=ecosystem;
        populateDonorTable();
    }

    private void populateDonorTable() {
        DefaultTableModel model = (DefaultTableModel) PatientJtable.getModel();

        model.setRowCount(0);
        for (PatientData network : ecosystem.getPatientDir().getPatientDirectory()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackjButton = new javax.swing.JButton();
        ViewjButton = new javax.swing.JButton();
        DeletejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatientJtable = new javax.swing.JTable();
        ViewjButton1 = new javax.swing.JButton();
        BackjButton1 = new javax.swing.JButton();
        DeletejButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BackjButton.setText("<<Back");

        ViewjButton.setText("View");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });

        DeletejButton.setText("Delete");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Donor Information");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Patient"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient"
            }
        ));
        jScrollPane2.setViewportView(PatientJtable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 404, 145));

        ViewjButton1.setText("View");
        ViewjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButton1ActionPerformed(evt);
            }
        });
        add(ViewjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 286, 84, -1));

        BackjButton1.setText("<<Back");
        BackjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButton1ActionPerformed(evt);
            }
        });
        add(BackjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 333, -1, -1));

        DeletejButton1.setText("Delete");
        DeletejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButton1ActionPerformed(evt);
            }
        });
        add(DeletejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 333, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("MANAGE PATIENT INFO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void ViewjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButton1ActionPerformed
        
        int selectedRow = PatientJtable.getSelectedRow();
        if(selectedRow>=0){
        
        PatientData patient = (PatientData)PatientJtable.getValueAt(selectedRow,0);
       // ViewFlight vf = new ViewFlight(csj, mts,airplane);
        ViewPatientJpanel vpj = new ViewPatientJpanel(displayJPanel,patient);
        displayJPanel.add("ViewFlight",vpj);
        CardLayout layout = (CardLayout)displayJPanel.getLayout();
        layout.next(displayJPanel);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a row");
        }
        
        
    }//GEN-LAST:event_ViewjButton1ActionPerformed

    private void BackjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButton1ActionPerformed
        // TODO add your handling code here:
        
        
        displayJPanel.remove(this);
        Component[] componentArray = displayJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_BackjButton1ActionPerformed

    private void DeletejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButton1ActionPerformed
       int selectedRow = PatientJtable.getSelectedRow();
        if(selectedRow>=0){
        
        PatientData patient = (PatientData)PatientJtable.getValueAt(selectedRow,0);
        ecosystem.getUserAccountDirectory().removeUserAccount(patient.getUsername());
        ecosystem.getPatientDir().removePatient(patient);
        populateDonorTable();
    }//GEN-LAST:event_DeletejButton1ActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackjButton;
    private javax.swing.JButton BackjButton1;
    private javax.swing.JButton DeletejButton;
    private javax.swing.JButton DeletejButton1;
    private javax.swing.JTable PatientJtable;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JButton ViewjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
