/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.SystemAdminWorkArea;

import java.awt.CardLayout;
import javax.swing.JPanel;
import medistopBackend.EcoSystem;

/**
 *
 * @author Virendra Rathore
 */

public class SystemAdministratorWorkAreaJPanel extends javax.swing.JPanel {
JPanel showPanel;
    EcoSystem ecosystem;
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdministratorWorkAreaJPanel(JPanel showPanel,EcoSystem ecosystem) {
        initComponents();
        this.ecosystem=ecosystem;
        this.showPanel=showPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageLocation = new javax.swing.JButton();
        btnManagePatient = new javax.swing.JButton();
        btnManageDonor = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnTitle = new javax.swing.JLabel();
        btnManageEnterAdministrator = new javax.swing.JButton();
        btnApplicationAnalytics = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("System Administrator Work Area"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageLocation.setText("Manage Location");
        btnManageLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLocationActionPerformed(evt);
            }
        });
        add(btnManageLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 202, -1));

        btnManagePatient.setText("Manage Patient");
        btnManagePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientActionPerformed(evt);
            }
        });
        add(btnManagePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 202, -1));

        btnManageDonor.setText("Manage Donor");
        btnManageDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDonorActionPerformed(evt);
            }
        });
        add(btnManageDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 202, -1));

        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 202, -1));

        btnTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnTitle.setText("SYSTEM ADMINISTRATOR");
        add(btnTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, 200, -1));

        btnManageEnterAdministrator.setText("Manage Enterprise admin");
        btnManageEnterAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterAdministratorActionPerformed(evt);
            }
        });
        add(btnManageEnterAdministrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        btnApplicationAnalytics.setText("Application Analysis");
        btnApplicationAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplicationAnalyticsActionPerformed(evt);
            }
        });
        add(btnApplicationAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 202, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLocationActionPerformed
        // TODO add your handling code here:
        ManageLocationJPanel manageLocationPanel=new  ManageLocationJPanel(showPanel, ecosystem);
        showPanel.add("manageLocationPanel",manageLocationPanel);
        CardLayout layout=(CardLayout)showPanel.getLayout();
        layout.next(showPanel);
        
    }//GEN-LAST:event_btnManageLocationActionPerformed

    private void btnManagePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientActionPerformed
        // TODO add your handling code here:
        ManagePatientJPanel managePatientPanel=new  ManagePatientJPanel(showPanel, ecosystem);
        showPanel.add("managePatientPanel",managePatientPanel);
        CardLayout layout=(CardLayout)showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnManagePatientActionPerformed

    private void btnManageDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDonorActionPerformed
        // TODO add your handling code here:
        ManageDonorJPanel manageDonorPanel=new  ManageDonorJPanel(showPanel, ecosystem);
        showPanel.add("manageDonorPanel",manageDonorPanel);
        CardLayout layout=(CardLayout)showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnManageDonorActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        // TODO add your handling code here:
        ManageEnterprisesJPanel manageEnterprisePanel=new  ManageEnterprisesJPanel(showPanel, ecosystem);
        showPanel.add("manageEnterprisePanel",manageEnterprisePanel);
        CardLayout layout=(CardLayout)showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageEnterAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterAdministratorActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdmin = new ManageEnterpriseAdminJPanel(showPanel,ecosystem);
        showPanel.add("manageEnterprisePanel",manageEnterpriseAdmin);
        CardLayout layout=(CardLayout)showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnManageEnterAdministratorActionPerformed

    private void btnApplicationAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplicationAnalyticsActionPerformed
        SystemAdminAnalyticsJPanel systemAdminAnalytics = new SystemAdminAnalyticsJPanel(showPanel,ecosystem);
        showPanel.add("systemAdminAnalyticsJPanel",systemAdminAnalytics);
        CardLayout layout=(CardLayout)showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnApplicationAnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplicationAnalytics;
    private javax.swing.JButton btnManageDonor;
    private javax.swing.JButton btnManageEnterAdministrator;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageLocation;
    private javax.swing.JButton btnManagePatient;
    private javax.swing.JLabel btnTitle;
    // End of variables declaration//GEN-END:variables
}
