/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.SystemAdminWorkArea;


import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import medistopBackend.EcoSystem;
import medistopBackend.UserData.*;

/**
 *
 * @author 
 */
public class ViewPatientJpanel extends javax.swing.JPanel 
{
    private JPanel displayJPanel;
    private EcoSystem system;
    private PatientDirectory patientDir;
    private PatientData patient;
    /**
     * Creates new form CreatePatientAccount
     */
    public ViewPatientJpanel(JPanel displayJPanel, PatientData patient) 
    {
        initComponents();
        this.system=system;
        this.displayJPanel=displayJPanel;
        this.patient = patient;
        txtAddress.setEnabled(false);
        txtCity.setEnabled(false);
        txtName.setEnabled(false);
        txtPhone.setEnabled(false);
        txtState.setEnabled(false);
        txtZipCode.setEnabled(false);
        txtUserName.setEnabled(false);
        txtAddress.setText(patient.getAddress());
        txtCity.setText(patient.getCity());
        txtName.setText(patient.getPatientName());
        txtZipCode.setText(String.valueOf(patient.getZipCode()));
        txtPhone.setText(patient.getContactNo());
        txtState.setText(patient.getState());
        txtUserName.setText(patient.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblUserPhoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Info"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setText("Patient's Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, -1, -1));
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 378, -1, -1));

        lblPhoneNumber.setText("Phone Number");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 136, -1, -1));

        lblAddress.setText("Address Line1");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, -1, -1));

        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 212, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("View PATIENT ACCOUNT");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 213, 35));

        lblState.setText("State");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 250, -1, -1));

        lblZipCode.setText("ZipCode");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 87, 181, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 131, 181, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 169, 181, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 207, 181, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 283, 181, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 245, 181, -1));

        btnCreate.setText("<<Back");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 378, -1, -1));

        lblUserName.setText("UserName");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 326, -1, -1));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 321, 181, -1));
        add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 87, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        backAction();
      
    }//GEN-LAST:event_btnCreateActionPerformed

    public void backAction()
    {
        displayJPanel.remove(this);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }
    
  /*  public String getGender()
    {
        if(maleRadioBtn.isSelected())
        {
            return "Male";
        }
       // else if(femaleRadioBtn.isSelected())
        {
            return "Female";
        }
        
        return null;
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
