/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medistopUI.patient;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 18577
 */
public class PatientWorkAreaPanel extends javax.swing.JPanel {
    DefaultTableModel appointmentDirectoryTableModel;
    DefaultTableModel appointmentHistoryTableModel;
    

    /** Creates new form DonorWorkAreaPanel */
    public PatientWorkAreaPanel() {
        initApptDirTableModel();
        initApptHistoryDirTableModel();
        initComponents();
    }
    
    public void initApptDirTableModel() {
        appointmentDirectoryTableModel = new DefaultTableModel();
        appointmentDirectoryTableModel.addColumn("Hospital");
        appointmentDirectoryTableModel.addColumn("Doctor");
        appointmentDirectoryTableModel.addColumn("Timestamp");
        appointmentDirectoryTableModel.addColumn("Status");
    }
    
    public void initApptHistoryDirTableModel() {
        
        appointmentHistoryTableModel = new DefaultTableModel();
        appointmentHistoryTableModel.addColumn("Hospital");   
        appointmentHistoryTableModel.addColumn("Doctor");  
        appointmentHistoryTableModel.addColumn("City");  
        appointmentHistoryTableModel.addColumn("Timestamp");    
        appointmentHistoryTableModel.addColumn("Disease");    


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donationTabbedPane = new javax.swing.JTabbedPane();
        menuPanel = new javax.swing.JPanel();
        deliveryDirLabel = new javax.swing.JLabel();
        delDirectoryScollPanel = new javax.swing.JScrollPane();
        charityDirTable = new javax.swing.JTable();
        deliveryDirLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        manageOrdersTab = new javax.swing.JPanel();
        propertyComboBox = new javax.swing.JComboBox<>();
        searchHeaderLabel = new javax.swing.JLabel();
        propertyValueTextField = new javax.swing.JTextField();
        donationListSearchButton = new javax.swing.JButton();
        resetTableButton = new javax.swing.JButton();
        searchCarCatalogScrollPanel = new javax.swing.JScrollPane();
        searchDonationCatalogTable = new javax.swing.JTable();
        deliveryDirLabel4 = new javax.swing.JLabel();
        helpTextLabel = new javax.swing.JLabel();

        donationTabbedPane.setForeground(new java.awt.Color(0, 0, 102));
        donationTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        deliveryDirLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel.setText("Book an appoinment with us to get the help you need...");

        charityDirTable.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        charityDirTable.setForeground(new java.awt.Color(0, 0, 102));
        charityDirTable.setModel(appointmentDirectoryTableModel);
        charityDirTable.setRowHeight(40);
        delDirectoryScollPanel.setViewportView(charityDirTable);

        deliveryDirLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel2.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel2.setText("Available appointments");

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 0, 102));
        registerBtn.setText("Book Appointment");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryDirLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delDirectoryScollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(deliveryDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deliveryDirLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delDirectoryScollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(backBtn))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("New Appointment", menuPanel);

        propertyComboBox.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        propertyComboBox.setForeground(new java.awt.Color(0, 0, 102));
        propertyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyComboBoxActionPerformed(evt);
            }
        });

        searchHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchHeaderLabel.setText("Select property to filter out records");

        propertyValueTextField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        propertyValueTextField.setForeground(new java.awt.Color(0, 0, 102));
        propertyValueTextField.setText(" ");

        donationListSearchButton.setText("Search");
        donationListSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationListSearchButtonActionPerformed(evt);
            }
        });

        resetTableButton.setText("Reset");
        resetTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTableButtonActionPerformed(evt);
            }
        });

        searchDonationCatalogTable.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        searchDonationCatalogTable.setForeground(new java.awt.Color(0, 0, 102));
        searchDonationCatalogTable.setModel(appointmentHistoryTableModel);
        searchDonationCatalogTable.setRowHeight(40);
        searchCarCatalogScrollPanel.setViewportView(searchDonationCatalogTable);

        deliveryDirLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deliveryDirLabel4.setForeground(new java.awt.Color(0, 0, 102));
        deliveryDirLabel4.setText("Appointment History");

        helpTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helpTextLabel.setForeground(new java.awt.Color(0, 0, 102));
        helpTextLabel.setText(" ");

        javax.swing.GroupLayout manageOrdersTabLayout = new javax.swing.GroupLayout(manageOrdersTab);
        manageOrdersTab.setLayout(manageOrdersTabLayout);
        manageOrdersTabLayout.setHorizontalGroup(
            manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrdersTabLayout.createSequentialGroup()
                .addGroup(manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageOrdersTabLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageOrdersTabLayout.createSequentialGroup()
                                .addComponent(propertyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(propertyValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(donationListSearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetTableButton))
                            .addComponent(helpTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageOrdersTabLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryDirLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCarCatalogScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        manageOrdersTabLayout.setVerticalGroup(
            manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrdersTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(deliveryDirLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchHeaderLabel)
                .addGap(18, 18, 18)
                .addGroup(manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(donationListSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageOrdersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(propertyComboBox)
                        .addComponent(propertyValueTextField)))
                .addGap(18, 18, 18)
                .addComponent(helpTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCarCatalogScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Appointment History", manageOrdersTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donationTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(donationTabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void propertyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyComboBoxActionPerformed
        // TODO add your handling code here:

        String propertyLabel = ((Object)propertyComboBox.getSelectedItem()).toString();
        String propertyName = ((Object)propertyComboBox.getSelectedItem()).toString();
        propertyValueTextField.setText("");

        helpTextLabel.setText("");
        switch (propertyName) {
            case "charityName": helpTextLabel.setText("Please type in valid charity name. Any other value would result in invalid filters."); break;
            case "charityCause": helpTextLabel.setText("Acceptable values: X1, X2 etc.");break;
 
        }

    }//GEN-LAST:event_propertyComboBoxActionPerformed

    private void donationListSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationListSearchButtonActionPerformed
        // TODO add your handling code here:

        String propertyLabel = ((Object)propertyComboBox.getSelectedItem()).toString();
        String propertyName = ((Object)propertyComboBox.getSelectedItem()).toString();

        String filterPropertyValue = propertyValueTextField.getText();

        System.out.println(propertyLabel + " ===  " + propertyName + " ==== " + filterPropertyValue);

//        ArrayList<Object> filteredList = new Utility().filterTable(propertyName, filterPropertyValue, carCatalog.getCars());
//
//        populateSearchTableHistory(filteredList);

    }//GEN-LAST:event_donationListSearchButtonActionPerformed

    private void resetTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTableButtonActionPerformed
        // TODO add your handling code here:
       // populateSearchTableHistory(carCatalog.getCars());
    }//GEN-LAST:event_resetTableButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_registerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable charityDirTable;
    private javax.swing.JScrollPane delDirectoryScollPanel;
    private javax.swing.JLabel deliveryDirLabel;
    private javax.swing.JLabel deliveryDirLabel2;
    private javax.swing.JLabel deliveryDirLabel4;
    private javax.swing.JButton donationListSearchButton;
    private javax.swing.JTabbedPane donationTabbedPane;
    private javax.swing.JLabel helpTextLabel;
    private javax.swing.JPanel manageOrdersTab;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JComboBox<String> propertyComboBox;
    private javax.swing.JTextField propertyValueTextField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetTableButton;
    private javax.swing.JScrollPane searchCarCatalogScrollPanel;
    private javax.swing.JTable searchDonationCatalogTable;
    private javax.swing.JLabel searchHeaderLabel;
    // End of variables declaration//GEN-END:variables

}
