/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.patient;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import medistopBackend.DB4OUtil.DB4OUtil;
import medistopBackend.EcoSystem;
import medistopBackend.Role.Donor;
import medistopBackend.Role.Patient;
import medistopBackend.UserData.DonorData;
import medistopBackend.UserData.PatientData;
import medistopUI.donor.*;
import medistopUtil.Utilities;

/**
 *
 * @author 18577
 */
public class ValidatePatientJPanel extends javax.swing.JPanel {
     private PatientData patientData;
    private JPanel bodyPanel;
    private EcoSystem ecosystem;
    private boolean isValidated;
    private String validationCode;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form ValidateDonorJPanel
     */
    public ValidatePatientJPanel(JPanel bodyPanel, EcoSystem ecosystem, String code, PatientData patient) {
        initComponents();
         this.bodyPanel = bodyPanel;
        this.ecosystem = ecosystem;
        validationCode = code;
        this.patientData = patient;
        setValidated(false);
    }
    
    
    public boolean getValidated() {
        return isValidated;
    }
    
    public void setValidated(boolean valid) {
       isValidated = valid;
       
       if (isValidated) {
           valAccL.setVisible(false);
           codeL.setVisible(false);
           codeTF.setVisible(false);
           helperLabel.setVisible(false);
           registerBtn.setVisible(false);

           setAccL.setVisible(true);
           userNameLabel.setVisible(true);
           usernameTF.setVisible(true);
           passPF.setVisible(true);
           paswdL.setVisible(true);
           saveBtn.setVisible(true);
       
       } else {

           valAccL.setVisible(true);
           codeL.setVisible(true);
           codeTF.setVisible(true);
           helperLabel.setVisible(true);
           registerBtn.setVisible(true);


           setAccL.setVisible(false);
           userNameLabel.setVisible(false);
           usernameTF.setVisible(false);
           passPF.setVisible(false);
           paswdL.setVisible(false);
           saveBtn.setVisible(false);
       
       }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAccL = new javax.swing.JLabel();
        codeL = new javax.swing.JLabel();
        codeTF = new javax.swing.JTextField();
        helperLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        valAccL = new javax.swing.JLabel();
        paswdL = new javax.swing.JLabel();
        passPF = new javax.swing.JPasswordField();
        saveBtn = new javax.swing.JButton();

        setAccL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        setAccL.setForeground(new java.awt.Color(0, 51, 102));
        setAccL.setText("SET YOUR ACCOUNT AS A DONOR");

        codeL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        codeL.setForeground(new java.awt.Color(0, 0, 102));
        codeL.setText("Code: ");

        codeTF.setForeground(new java.awt.Color(0, 0, 102));
        codeTF.setText(" ");

        helperLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helperLabel.setForeground(new java.awt.Color(0, 0, 102));
        helperLabel.setText("Please check your email you will have received a code. Please check the spam folder as well.");

        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 0, 102));
        registerBtn.setText("Validate");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 0, 102));
        userNameLabel.setText("Username:");

        usernameTF.setForeground(new java.awt.Color(0, 0, 102));
        usernameTF.setText(" ");

        valAccL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        valAccL.setForeground(new java.awt.Color(0, 51, 102));
        valAccL.setText("VALIDATE YOUR ACCOUNT AS A PATIENT");

        paswdL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paswdL.setForeground(new java.awt.Color(0, 0, 102));
        paswdL.setText("Password:");

        passPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPFActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 0, 102));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paswdL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(passPF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codeL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(valAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeL)
                    .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helperLabel)
                .addGap(52, 52, 52)
                .addComponent(registerBtn)
                .addGap(29, 29, 29)
                .addComponent(setAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paswdL)
                    .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(saveBtn)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(valAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(647, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        boolean valid = Utilities.getTrimmedText(codeTF).equals(validationCode);
        setValidated(valid);


    }//GEN-LAST:event_registerBtnActionPerformed

    private void passPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPFActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        String userName = Utilities.getTrimmedText(usernameTF);
        String password = String.valueOf(passPF.getPassword());
        
        boolean result = ecosystem.getUserAccountDirectory().isUserNameUnique(userName);
        
        if (result) {
            patientData.setUsername(userName);
            ecosystem.getUserAccountDirectory().newPatientAccount(userName, password,
                    patientData, new Patient());
            ecosystem.getPatientDir().addPat(patientData);
            dB4OUtil.storeSystem(ecosystem);

            JOptionPane.showMessageDialog(null, "You have been officially registered as Donor \nPlease Login to start donating.. ",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
            saveBtn.setEnabled(false);
            usernameTF.setEditable(false);
            passPF.setEditable(false);
            usernameTF.setText("");
            passPF.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Try a different username, current username already exists","Error", JOptionPane.ERROR_MESSAGE);
            usernameTF.setText("");
            passPF.setText("");
        }
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeL;
    private javax.swing.JTextField codeTF;
    private javax.swing.JLabel helperLabel;
    private javax.swing.JPasswordField passPF;
    private javax.swing.JLabel paswdL;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel setAccL;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JLabel valAccL;
    // End of variables declaration//GEN-END:variables
}
