/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.FundManager;

import medistopBackend.Funds.Organisation.FundsOrganisationManager;
import medistopBackend.EcoSystem;
import medistopBackend.Enterprise.FundingEnterprise;
import medistopBackend.Network.Network;
import medistopBackend.UserAccount.UserAccount;
import medistopBackend.WorkQueue.HospitalFundsRequestWorkQueue;
import medistopBackend.WorkQueue.WorkRequest;
import medistopBackend.Funds.Donation.FundsInfo;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Virendra Rathore
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel 
{
    private JPanel showPanel;
    private FundingEnterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    private Network network;
    String funds;
    /**
     * Creates new form ManagerWorkAreaJPanel
     */
    public ManagerWorkAreaJPanel(JPanel showPanel, UserAccount userAccount, FundsOrganisationManager organisation, FundingEnterprise enterprise, Network network, EcoSystem ecoSystem) 
    {
        initComponents();
        this.showPanel = showPanel;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        this.network = network;
        
        lblValue.setText(enterprise.getName());    
        
        float amountReceived = 0;
        
        try
        {
            for(FundsInfo dd : ecoSystem.getDonationDirectory().getFundsDirectory())
            {
                if(dd.getFundsOrgName().equalsIgnoreCase(lblValue.getText()))
                {
                    amountReceived += Float.parseFloat(dd.getDonation());
                }
            }
        
            lblFundsValue.setText(String.valueOf(amountReceived));
            float sumUsed = fundCalculation();
            float sumAvailable = (amountReceived-sumUsed);
            funds = String.valueOf(amountReceived-sumUsed);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Server Down", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public float fundCalculation()
    {
        float sum =0;
        
        for(WorkRequest request : network.getFundsRequests().getWorkRequestList())
            {
                HospitalFundsRequestWorkQueue hospitalFundsRequestWorkQueue = (HospitalFundsRequestWorkQueue)request;
                
                if(hospitalFundsRequestWorkQueue.getMessage().equalsIgnoreCase("Acknowledged") && hospitalFundsRequestWorkQueue.getFunderName().equalsIgnoreCase(enterprise.getName()))
                {
                    sum += hospitalFundsRequestWorkQueue.getAmount();
                }
            }
        
        lblFundsUsed.setText(String.valueOf(sum));
        
        return sum;
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnViewDonations = new javax.swing.JButton();
        btnPickUp = new javax.swing.JButton();
        lblFunds = new javax.swing.JLabel();
        lblFundsValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFundsUsed = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Funding Manager"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Songti TC", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 102));
        lblTitle.setText("FUNDING MANAGER:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 260, -1));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 102));
        lblName.setText("Funding Organisation Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, -1, -1));
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 72, -1, -1));

        btnViewDonations.setForeground(new java.awt.Color(0, 51, 102));
        btnViewDonations.setText("View Donations");
        btnViewDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationsActionPerformed(evt);
            }
        });
        add(btnViewDonations, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 163, 30));

        btnPickUp.setForeground(new java.awt.Color(0, 51, 102));
        btnPickUp.setText("Pick New Case");
        btnPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPickUpActionPerformed(evt);
            }
        });
        add(btnPickUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 163, 30));

        lblFunds.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblFunds.setForeground(new java.awt.Color(0, 51, 102));
        lblFunds.setText("Funds Received");
        add(lblFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        lblFundsValue.setText("value");
        add(lblFundsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 116, 80, 20));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Funds Used");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 161, -1, -1));

        lblFundsUsed.setText("0");
        add(lblFundsUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 20, -1));

        btnRefresh.setForeground(new java.awt.Color(0, 51, 102));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationsActionPerformed
        CompleteDonationRelatedDetailsJPanel completeDonationRelatedDetailsJPanel = new CompleteDonationRelatedDetailsJPanel(showPanel, ecoSystem,enterprise, userAccount);
        showPanel.add("completeDonationRelatedDetailsJPanel", completeDonationRelatedDetailsJPanel);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnViewDonationsActionPerformed

    private void btnPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickUpActionPerformed
        PatientsTreatmentSponsoringDetails patientsTreatmentSponsoringDetails = new PatientsTreatmentSponsoringDetails(showPanel,enterprise,network,ecoSystem, userAccount,funds);
        showPanel.add("patientsTreatmentSponsoringDetails", patientsTreatmentSponsoringDetails);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.next(showPanel);
    }//GEN-LAST:event_btnPickUpActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        float sum =0;
        
        for(WorkRequest request : network.getFundsRequests().getWorkRequestList())
            {
                HospitalFundsRequestWorkQueue hospitalFundsRequestWorkQueue = (HospitalFundsRequestWorkQueue)request;
                
                if(hospitalFundsRequestWorkQueue.getMessage().equalsIgnoreCase("Acknowledged") && hospitalFundsRequestWorkQueue.getFunderName().equalsIgnoreCase(enterprise.getName()))
                {
                    sum += hospitalFundsRequestWorkQueue.getAmount();
                }
            }
        
        lblFundsUsed.setText(String.valueOf(sum));
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPickUp;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDonations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFunds;
    private javax.swing.JLabel lblFundsUsed;
    private javax.swing.JLabel lblFundsValue;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
