/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medistopUI.Assistant;

import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import medistopBackend.EcoSystem;
import medistopBackend.Employee.Employee;
import medistopBackend.Enterprise.Enterprise;
import medistopBackend.Hospital.Appointment.AppointmentDetails;
import medistopBackend.Hospital.Organisation.HospitalOrganisationAssistant;
import medistopBackend.Network.Network;
import medistopBackend.Organisation.Organisation;
import medistopBackend.UserAccount.UserAccount;
import medistopBackend.WorkQueue.AssistantAddingTimingsWorkQueue;
import medistopBackend.WorkQueue.DoctorAssistantAccountingWorkQueue;
import medistopBackend.WorkQueue.HospitalFundsRequestWorkQueue;
import medistopBackend.WorkQueue.PatientBookingWorkQueue;
import medistopBackend.WorkQueue.ReceivedFundWorkRequest;
import medistopBackend.WorkQueue.WorkRequest;

/**
 *
 * @author Zeenia
 */
public class AssistantWorkAreaPanel extends javax.swing.JPanel {

    private JPanel displayJPanel;
    private UserAccount ua;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    private Network network;
    private HospitalOrganisationAssistant hospitalAssistant;
    private AssistantAddingTimingsWorkQueue assistantAddSlot;
    private DefaultComboBoxModel minuteModel;
    
    /**
     * Creates new form AssistantWorkAreaPanel
     */
//    public AssistantWorkAreaPanel(JPanel dispJPanel, UserAccount account, HospitalOrganisationAssistant organisation, Enterprise enterprise,EcoSystem system) {
//        initComponents();
//        this.displayJPanel = dispJPanel;
//        this.ua = account;
//        this.hospitalAssistant = organisation;
//        this.enterprise = enterprise;
//        this.ecosystem = system;
//        lblAssistantName.setText(ua.getUsername());
//        populateAppointmentTable();
//        populateAcknowledgmentTable();
//
//
//    }
    
    public AssistantWorkAreaPanel(JPanel dispJPanel, UserAccount account, HospitalOrganisationAssistant organisation, Enterprise enterprise,Network net,EcoSystem system) {
        initComponents();
        this.displayJPanel = dispJPanel;
        this.ua = account;
        this.hospitalAssistant = organisation;
        this.enterprise = enterprise;
        this.ecosystem = system;
        this.network = net;
        populateMinuteComboBoxModel();
        populateFundingRequestsTable();
        populateComboDoctor();
        populateAppointmentTable();
        populateAcknowledgmentTable();
        lblAssistantName.setText(ua.getEmployee().getEmployeeName());
        lblAssistantName1.setText(ua.getEmployee().getEmployeeName());
        lblAssistantName2.setText(ua.getEmployee().getEmployeeName());
        lblAssistantName3.setText(ua.getEmployee().getEmployeeName());

    }
    
    public void populateMinuteComboBoxModel() {
        minuteModel = new DefaultComboBoxModel();
        minuteModel.addElement("mm");
        
        for (int i=0; i<60; i++) {

            minuteModel.addElement(String.valueOf(i));
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        donationTabbedPane = new javax.swing.JTabbedPane();
        manageFundingRequestsPanel = new javax.swing.JPanel();
        helpTextLabel1 = new javax.swing.JLabel();
        deliveryDirLabel8 = new javax.swing.JLabel();
        menuItemName14 = new javax.swing.JLabel();
        txtFundReqd = new javax.swing.JTextField();
        btnRaiseFundingRequest = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFundingRequests = new javax.swing.JTable();
        lblWelcome1 = new javax.swing.JLabel();
        lblAssistantName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fundingAcknowledgementPanel = new javax.swing.JPanel();
        deliveryDirLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAcknowledgement = new javax.swing.JTable();
        lblWelcome2 = new javax.swing.JLabel();
        lblAssistantName2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manageAppointmentsPanel = new javax.swing.JPanel();
        helpTextLabel = new javax.swing.JLabel();
        deliveryDirLabel7 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointment = new javax.swing.JTable();
        btnReject = new javax.swing.JButton();
        lblWelcome3 = new javax.swing.JLabel();
        lblAssistantName3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageDocSlotsPanel = new javax.swing.JPanel();
        deliveryDirLabel5 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblAssistantName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        menuItemName6 = new javax.swing.JLabel();
        comboManageSlots = new javax.swing.JComboBox();
        menuItemName12 = new javax.swing.JLabel();
        comboMonth = new javax.swing.JComboBox();
        comboDay = new javax.swing.JComboBox();
        comboYear = new javax.swing.JComboBox();
        menuItemName13 = new javax.swing.JLabel();
        comboHour = new javax.swing.JComboBox();
        comboMinute = new javax.swing.JComboBox();
        btnAddSlot = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setForeground(new java.awt.Color(102, 153, 255));

        jPanel1.setPreferredSize(new java.awt.Dimension(1925, 857));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1925, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );

        donationTabbedPane.setForeground(new java.awt.Color(0, 0, 102));
        donationTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        manageFundingRequestsPanel.setBackground(new java.awt.Color(255, 255, 255));

        helpTextLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helpTextLabel1.setForeground(new java.awt.Color(0, 0, 102));
        helpTextLabel1.setText(" ");

        deliveryDirLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel8.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel8.setText("ASSISTANT WORK AREA");

        menuItemName14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName14.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName14.setText("Funding Required:      $");

        btnRaiseFundingRequest.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnRaiseFundingRequest.setForeground(new java.awt.Color(0, 0, 102));
        btnRaiseFundingRequest.setText("Raise Funding Request");
        btnRaiseFundingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseFundingRequestActionPerformed(evt);
            }
        });

        tblFundingRequests.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        tblFundingRequests.setForeground(new java.awt.Color(0, 0, 102));
        tblFundingRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Name", "Prescription", "Funding Required", "Funding Approved"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFundingRequests.setRowHeight(40);
        jScrollPane4.setViewportView(tblFundingRequests);

        lblWelcome1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(0, 0, 102));
        lblWelcome1.setText("Welcome ");

        lblAssistantName1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAssistantName1.setForeground(new java.awt.Color(0, 0, 102));
        lblAssistantName1.setText("value");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medistopUI.images/nurse.jpg"))); // NOI18N

        javax.swing.GroupLayout manageFundingRequestsPanelLayout = new javax.swing.GroupLayout(manageFundingRequestsPanel);
        manageFundingRequestsPanel.setLayout(manageFundingRequestsPanelLayout);
        manageFundingRequestsPanelLayout.setHorizontalGroup(
            manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                .addGroup(manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(lblWelcome1)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssistantName1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                        .addGroup(manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(helpTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(deliveryDirLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                                .addComponent(menuItemName14, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFundReqd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRaiseFundingRequest))))
                .addContainerGap(743, Short.MAX_VALUE))
        );
        manageFundingRequestsPanelLayout.setVerticalGroup(
            manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageFundingRequestsPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(deliveryDirLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWelcome1)
                            .addComponent(lblAssistantName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpTextLabel1))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(manageFundingRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName14)
                    .addComponent(txtFundReqd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnRaiseFundingRequest)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Funding Requests", manageFundingRequestsPanel);

        fundingAcknowledgementPanel.setBackground(new java.awt.Color(255, 255, 255));

        deliveryDirLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel11.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel11.setText("ASSISTANT WORK AREA");

        tblAcknowledgement.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        tblAcknowledgement.setForeground(new java.awt.Color(0, 0, 102));
        tblAcknowledgement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient", "Date Acknowledged", "Charity", "Charity Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblAcknowledgement);

        lblWelcome2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome2.setForeground(new java.awt.Color(0, 0, 102));
        lblWelcome2.setText("Welcome ");

        lblAssistantName2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAssistantName2.setForeground(new java.awt.Color(0, 0, 102));
        lblAssistantName2.setText("value");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medistopUI.images/nurse.jpg"))); // NOI18N

        javax.swing.GroupLayout fundingAcknowledgementPanelLayout = new javax.swing.GroupLayout(fundingAcknowledgementPanel);
        fundingAcknowledgementPanel.setLayout(fundingAcknowledgementPanelLayout);
        fundingAcknowledgementPanelLayout.setHorizontalGroup(
            fundingAcknowledgementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundingAcknowledgementPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(fundingAcknowledgementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundingAcknowledgementPanelLayout.createSequentialGroup()
                        .addGroup(fundingAcknowledgementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundingAcknowledgementPanelLayout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(deliveryDirLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundingAcknowledgementPanelLayout.createSequentialGroup()
                                .addComponent(lblWelcome2)
                                .addGap(18, 18, 18)
                                .addComponent(lblAssistantName2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)))
                .addContainerGap(786, Short.MAX_VALUE))
        );
        fundingAcknowledgementPanelLayout.setVerticalGroup(
            fundingAcknowledgementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundingAcknowledgementPanelLayout.createSequentialGroup()
                .addGroup(fundingAcknowledgementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundingAcknowledgementPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(deliveryDirLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(fundingAcknowledgementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWelcome2)
                            .addComponent(lblAssistantName2)))
                    .addGroup(fundingAcknowledgementPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab(" Acknowledgments", fundingAcknowledgementPanel);

        manageAppointmentsPanel.setBackground(new java.awt.Color(255, 255, 255));

        helpTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        helpTextLabel.setForeground(new java.awt.Color(0, 0, 102));
        helpTextLabel.setText(" ");

        deliveryDirLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel7.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel7.setText("ASSISTANT WORK AREA");

        btnAccept.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(0, 0, 102));
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        tblAppointment.setForeground(new java.awt.Color(0, 0, 102));
        tblAppointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient ID", "Appointment Details", "Type Of Consultation", "Doctor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAppointment.setRowHeight(40);
        jScrollPane1.setViewportView(tblAppointment);

        btnReject.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnReject.setForeground(new java.awt.Color(0, 0, 102));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        lblWelcome3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome3.setForeground(new java.awt.Color(0, 0, 102));
        lblWelcome3.setText("Welcome ");

        lblAssistantName3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAssistantName3.setForeground(new java.awt.Color(0, 0, 102));
        lblAssistantName3.setText("value");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medistopUI.images/nurse.jpg"))); // NOI18N

        javax.swing.GroupLayout manageAppointmentsPanelLayout = new javax.swing.GroupLayout(manageAppointmentsPanel);
        manageAppointmentsPanel.setLayout(manageAppointmentsPanelLayout);
        manageAppointmentsPanelLayout.setHorizontalGroup(
            manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                .addGroup(manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(helpTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                        .addGroup(manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(deliveryDirLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAppointmentsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblWelcome3)
                                .addGap(18, 18, 18)
                                .addComponent(lblAssistantName3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)))
                        .addComponent(jLabel2))
                    .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(797, Short.MAX_VALUE))
        );
        manageAppointmentsPanelLayout.setVerticalGroup(
            manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                .addGroup(manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(manageAppointmentsPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(deliveryDirLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWelcome3)
                            .addComponent(lblAssistantName3))))
                .addGap(171, 171, 171)
                .addComponent(helpTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(385, 385, 385)
                .addGroup(manageAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Manage Appointments", manageAppointmentsPanel);

        manageDocSlotsPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageDocSlotsPanel.setForeground(new java.awt.Color(0, 0, 102));
        manageDocSlotsPanel.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N

        deliveryDirLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        deliveryDirLabel5.setForeground(new java.awt.Color(255, 51, 51));
        deliveryDirLabel5.setText("ASSISTANT WORK AREA");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 102));
        lblWelcome.setText("Welcome ");

        lblAssistantName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAssistantName.setText("value");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medistopUI.images/nurse.jpg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));

        menuItemName6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName6.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName6.setText("Doctor Name:");

        menuItemName12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName12.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName12.setText("Date:");

        comboMonth.setForeground(new java.awt.Color(0, 0, 102));
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonthActionPerformed(evt);
            }
        });

        comboDay.setForeground(new java.awt.Color(0, 0, 102));
        comboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        comboYear.setForeground(new java.awt.Color(0, 0, 102));
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "2021", "2022", "2023", "2024", "2025" }));
        comboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearActionPerformed(evt);
            }
        });

        menuItemName13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItemName13.setForeground(new java.awt.Color(0, 0, 102));
        menuItemName13.setText("Time: ");

        comboHour.setForeground(new java.awt.Color(0, 0, 102));
        comboHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HH", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        comboHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHourActionPerformed(evt);
            }
        });

        comboMinute.setForeground(new java.awt.Color(0, 0, 102));
        comboMinute.setModel(minuteModel);
        comboMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMinuteActionPerformed(evt);
            }
        });

        btnAddSlot.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnAddSlot.setForeground(new java.awt.Color(0, 0, 102));
        btnAddSlot.setText("Add Slot Available");
        btnAddSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSlotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(menuItemName6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboManageSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(menuItemName12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(menuItemName13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(comboHour, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(comboMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName6)
                    .addComponent(comboManageSlots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuItemName12)
                    .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuItemName13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnAddSlot)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout manageDocSlotsPanelLayout = new javax.swing.GroupLayout(manageDocSlotsPanel);
        manageDocSlotsPanel.setLayout(manageDocSlotsPanelLayout);
        manageDocSlotsPanelLayout.setHorizontalGroup(
            manageDocSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDocSlotsPanelLayout.createSequentialGroup()
                .addGroup(manageDocSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageDocSlotsPanelLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(manageDocSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deliveryDirLabel5)
                            .addGroup(manageDocSlotsPanelLayout.createSequentialGroup()
                                .addComponent(lblWelcome)
                                .addGap(18, 18, 18)
                                .addComponent(lblAssistantName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(manageDocSlotsPanelLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(962, Short.MAX_VALUE))
        );
        manageDocSlotsPanelLayout.setVerticalGroup(
            manageDocSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDocSlotsPanelLayout.createSequentialGroup()
                .addGroup(manageDocSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageDocSlotsPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(deliveryDirLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(manageDocSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWelcome)
                            .addComponent(lblAssistantName)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        donationTabbedPane.addTab("Manage Doctor Slots", manageDocSlotsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donationTabbedPane)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSlotActionPerformed
        // TODO add your handling code here:
        String day,month,year, hour, minute;
        
           day = (String)comboDay.getSelectedItem();
           month = (String)comboMonth.getSelectedItem();
           year = (String)comboYear.getSelectedItem();
           hour = (String) comboHour.getSelectedItem();
           minute =  (String) comboMinute.getSelectedItem();
           int date=1,monthValue=1,yearValue=1990, hourValue=0, minuteValue =0;

           try {
                date = Integer.parseInt(day);
                monthValue = Integer.parseInt(month);
                yearValue = Integer.parseInt(year);
                hourValue = Integer.parseInt(hour);
                minuteValue = Integer.parseInt(minute);



           } catch (Exception e) {

               JOptionPane.showMessageDialog(null,
                       "Incorrect values for date, month, year", "Error", JOptionPane.INFORMATION_MESSAGE);

               return;
           }
           

           assistantAddSlot = new AssistantAddingTimingsWorkQueue();
           
           assistantAddSlot.setTimings(LocalDateTime.of(yearValue, monthValue, hourValue, minuteValue, 0));
           for(Network net : ecosystem.getNetworkList())
           {
               for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList())
               {
                   if(ent.getName().equalsIgnoreCase(enterprise.getName()))
                   {
                       assistantAddSlot.setCity(net.getNetworkName());
                   }
               }
           }
           Employee e = new Employee();
           e = (Employee)comboManageSlots.getSelectedItem();
           
           assistantAddSlot.setDoctor(e.getEmployeeName());
           assistantAddSlot.setSender(ua);
           assistantAddSlot.setStatus("Available");
           assistantAddSlot.setMessage("Available slots");
           assistantAddSlot.setHospitalName(enterprise.getName());
           assistantAddSlot.setCity(network.getNetworkName());
           ecosystem.getPatientDir().getWorkQueue().getWorkRequestList().add(assistantAddSlot);
           ua.getWorkQueue().getWorkRequestList().add(assistantAddSlot);
            
           JOptionPane.showMessageDialog(null, "Doctor's  available slot added successfully!!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddSlotActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblAppointment.getSelectedRow();
            if(selectedRow>0)
            {
                PatientBookingWorkQueue patientBooking = (PatientBookingWorkQueue)tblAppointment.getValueAt(selectedRow, 0);
                
                if(patientBooking.getStatus().equals("Approved"))
                {
                    JOptionPane.showMessageDialog(null,"Patient appointment already approved!","Warning",JOptionPane.WARNING_MESSAGE);
                }
                else if(patientBooking.getStatus().equals("Rejected"))
                {
                    JOptionPane.showMessageDialog(null,"Patient appointment already rejected!","Warning",JOptionPane.WARNING_MESSAGE);
                }
                
                else
                {
                    patientBooking.setStatus("Approved");
                    populateAppointmentTable();
                    AppointmentDetails appointment = ecosystem.getAppointmentDirectory().createAppointment();
                    appointment.setCityOfTreated(patientBooking.getCity());
                    appointment.setDoctorName(patientBooking.getDoctor());
                    appointment.setHospitalName(patientBooking.getHospitalName());
                    appointment.setPatient(patientBooking.getPatient());
                    appointment.setDate(new Date());
                
                    JOptionPane.showMessageDialog(null, "Patient Appointment Approved!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Please select a patient record first!","Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnAcceptActionPerformed
    }
    
    private void btnRaiseFundingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseFundingRequestActionPerformed
        // TODO add your handling code here:
         try{
         int selectedRow = tblFundingRequests.getSelectedRow();
         
         if(selectedRow>0)
            {
                DoctorAssistantAccountingWorkQueue  assistantAccounting = (DoctorAssistantAccountingWorkQueue)tblFundingRequests.getValueAt(selectedRow, 0);
                HospitalFundsRequestWorkQueue fundsRequest = new HospitalFundsRequestWorkQueue();
                
                fundsRequest.setSender(ua);
                fundsRequest.setAmount(Float.parseFloat(txtFundReqd.getText()));
                fundsRequest.setHospitalName(enterprise.getName());
                fundsRequest.setMessage("Sponsorship Required");
                fundsRequest.setPatientName(assistantAccounting.getApd().getPatient().getPatientName());
                fundsRequest.setCity(network.getNetworkName());
                fundsRequest.setStatus("No");
                
                for(Network network : ecosystem.getNetworkList())
                {
                    if(network.getNetworkName().equals(this.network.getNetworkName()))
                    {
                            assistantAccounting.setMessage("Sent");
                            network.getFundsRequests().getWorkRequestList().add(fundsRequest);
                            ua.getWorkQueue().getWorkRequestList().add(fundsRequest);
                            
                        JOptionPane.showMessageDialog(null, "Posted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        break;
                }
                }
                txtFundReqd.setText("");
            }
        
            else
            {
                JOptionPane.showMessageDialog(null, "Please select a patient to proceed!","Warning", JOptionPane.WARNING_MESSAGE);
                    }
         }
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please enter proper values!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRaiseFundingRequestActionPerformed

    private void comboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboYearActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblAppointment.getSelectedRow();
         if(selectedRow>0)
            {
                PatientBookingWorkQueue patientBooking = (PatientBookingWorkQueue)tblAppointment.getValueAt(selectedRow, 0);
                
                if(patientBooking.getStatus().equals("Approved"))
                {
                    JOptionPane.showMessageDialog(null,"Patient appointment already approved!","Warning",JOptionPane.WARNING_MESSAGE);
                }
                else if(patientBooking.getStatus().equals("Rejected"))
                {
                    JOptionPane.showMessageDialog(null,"Patient appointment already rejected!","Warning",JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    patientBooking.setStatus("Rejected");
                    populateAppointmentTable();
                    JOptionPane.showMessageDialog(null, "Patient Appointment Approved!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
              
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Please Select any Patient appointment to proceed","Warning", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void comboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMonthActionPerformed

    private void comboMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMinuteActionPerformed

    private void comboHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAddSlot;
    private javax.swing.JButton btnRaiseFundingRequest;
    private javax.swing.JButton btnReject;
    private javax.swing.JComboBox comboDay;
    private javax.swing.JComboBox comboHour;
    private javax.swing.JComboBox comboManageSlots;
    private javax.swing.JComboBox comboMinute;
    private javax.swing.JComboBox comboMonth;
    private javax.swing.JComboBox comboYear;
    private javax.swing.JLabel deliveryDirLabel11;
    private javax.swing.JLabel deliveryDirLabel5;
    private javax.swing.JLabel deliveryDirLabel7;
    private javax.swing.JLabel deliveryDirLabel8;
    private javax.swing.JTabbedPane donationTabbedPane;
    private javax.swing.JPanel fundingAcknowledgementPanel;
    private javax.swing.JLabel helpTextLabel;
    private javax.swing.JLabel helpTextLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAssistantName;
    private javax.swing.JLabel lblAssistantName1;
    private javax.swing.JLabel lblAssistantName2;
    private javax.swing.JLabel lblAssistantName3;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JLabel lblWelcome3;
    private javax.swing.JPanel manageAppointmentsPanel;
    private javax.swing.JPanel manageDocSlotsPanel;
    private javax.swing.JPanel manageFundingRequestsPanel;
    private javax.swing.JLabel menuItemName12;
    private javax.swing.JLabel menuItemName13;
    private javax.swing.JLabel menuItemName14;
    private javax.swing.JLabel menuItemName6;
    private javax.swing.JTable tblAcknowledgement;
    private javax.swing.JTable tblAppointment;
    private javax.swing.JTable tblFundingRequests;
    private javax.swing.JTextField txtFundReqd;
    // End of variables declaration//GEN-END:variables

    
//To populate appointment table
public void populateAppointmentTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblAppointment.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : hospitalAssistant.getIncomingPatients().getWorkRequestList())
        {
            PatientBookingWorkQueue patient = new PatientBookingWorkQueue();
            patient = (PatientBookingWorkQueue)request;
            Object[] row = new Object[5];
            row[0] = patient;
            row[1] = patient.getPatient().getPatientId();
            row[2] = patient.getMessage();
            row[3] = patient.getSender();
            row[4] = request.getStatus();
            
            model.addRow(row);
        }          
    }

//To populate funding acknowledgment table
 public void populateAcknowledgmentTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblAcknowledgement.getModel();
        
            model.setRowCount(0);
        
            for(WorkRequest request : hospitalAssistant.getFundsReceived().getWorkRequestList())
            {
                ReceivedFundWorkRequest t = new ReceivedFundWorkRequest();
                t = (ReceivedFundWorkRequest)request;
                
                if(enterprise.getName().equalsIgnoreCase(t.getHospitalName()))
                {
                    Object[] row = new Object[4];
                    row[0] = t;
                    row[1] = t.getDateReceived();
                    row[2] = t.getFunderName();
                    row[3] = t.getCity();
            
                    model.addRow(row);
                }
            }
    }
 
//To populate funding request table
public void populateFundingRequestsTable(){
    DefaultTableModel model = (DefaultTableModel) tblFundingRequests.getModel();
        
            model.setRowCount(0);
        
            for(WorkRequest request : hospitalAssistant.getFundApplicationQueue().getWorkRequestList())
            {
                DoctorAssistantAccountingWorkQueue accounting = new DoctorAssistantAccountingWorkQueue();
                accounting = (DoctorAssistantAccountingWorkQueue)request;
                Object[] row = new Object[4];
                row[0] = accounting;
                row[1] = accounting.getPrescribed();
                row[2] = accounting.isFundingRequired();
                row[3] = accounting.isFundingApproved();
            
                model.addRow(row);
            }  
}

public void populateComboDoctor(){
    comboManageSlots.removeAllItems();
        for(Organisation o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o.getName().equals("Doctor Organisation"))
            {
                for(Employee e: o.getEmployeeDirectory().getEmployeeDirectory())
                {
                    comboManageSlots.addItem(e);
                }
            }
        }
}
}
